---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: resource-topology-exporter-ds
spec:
  selector:
      matchLabels:
        name: resource-topology
  template:
    metadata:
      labels:
        name: resource-topology
    spec:
      readinessGates:
        - conditionType: "PodresourcesFetched"
        - conditionType: "NodeTopologyUpdated"
      serviceAccountName: rte
      containers:
      - name: resource-topology-exporter-container
        image: ${RTE_CONTAINER_IMAGE}
        command:
        - /bin/resource-topology-exporter
        args:
          - --sleep-interval=${RTE_POLL_INTERVAL}
          - --sysfs=/host-sys
          - --kubelet-state-dir=/host-var/lib/kubelet
          - --kubelet-config-file=/host-var/lib/kubelet/config.yaml
          - --podresources-socket=unix:///host-var/lib/kubelet/pod-resources/kubelet.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REFERENCE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REFERENCE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REFERENCE_CONTAINER_NAME
          value: shared-pool-container
        - name: METRICS_PORT
          value: "${METRICS_PORT}"
        volumeMounts:
          - name: host-sys
            mountPath: "/host-sys"
            readOnly: true
          - name: host-kubelet-state
            mountPath: "/host-var/lib/kubelet"
          - name: rte-config
            mountPath: "/etc/resource-topology-exporter"
        ports:
          - name: metrics-port
            containerPort: ${METRICS_PORT}
      - name: shared-pool-container
        image: gcr.io/google_containers/pause-amd64:3.0
      volumes:
      - name: host-sys
        hostPath:
          path: "/sys"
      - name: host-kubelet-state
        hostPath:
          path: "/var/lib/kubelet"
      - name: rte-config
        configMap:
          name: rte-config
          optional: true
