---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: resource-topology-exporter-ds
spec:
  selector:
      matchLabels:
        name: resource-topology
  template:
    metadata:
      labels:
        name: resource-topology
    spec:
      serviceAccountName: rte
      containers:
      - name: resource-topology-exporter-container
        image: ${RTE_CONTAINER_IMAGE}
        command:
        - /bin/resource-topology-exporter
        args:
          - -v=5
          - --sleep-interval=${RTE_POLL_INTERVAL}
          - --sysfs=/host-sys
          - --notify-file=/host-run/rte/notify
          - --topology-manager-policy=single-numa-node
          - --topology-manager-scope=container
          - --podresources-socket=unix:///host-podresources/kubelet.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REFERENCE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REFERENCE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REFERENCE_CONTAINER_NAME
          value: shared-pool-container
        - name: METRICS_PORT
          value: "${METRICS_PORT}"
        volumeMounts:
          - name: host-sys
            mountPath: "/host-sys"
            readOnly: true
          - name: host-podresources
            mountPath: "/host-podresources"
          - name: host-rte-notification
            mountPath: "/host-run/rte"
          - name: rte-config
            mountPath: "/etc/resource-topology-exporter"
        ports:
          - name: metrics-port
            containerPort: ${METRICS_PORT}
      - name: shared-pool-container
        image: gcr.io/google_containers/pause-amd64:3.0
      volumes:
      - name: host-sys
        hostPath:
          path: "/sys"
      - name: host-podresources
        hostPath:
          path: "/var/lib/kubelet/pod-resources/"
      - name: host-rte-notification
        hostPath:
          path: "/run/rte"
      - name: rte-config
        configMap:
          name: rte-config
          optional: true
