---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rte-config
  namespace: default
data:
  config.yaml: |
    # key = node name, value = list of resources to be excluded.
    # use * to exclude from all nodes.
    # an example for how the exclude list should looks like
    # excludelist:
    #   node1: [cpu]
    #   node2: [memory, example/deviceA]
    #   *: [cpu]
